# Funding options for R Observatory
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [coatless]
patreon: coatless
buy_me_a_coffee: coatless
thanks_dev: u/gh/coatless
